[[redirects]]
  from = "https://www.blog.wildanfauzy.com/*"
  to = "https://blog.wildanfauzy.com/$1"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"